[package]
name = "geist_common"
version = "0.1.0"
edition = "2021"
description = "Geist common messages for running a Geist app"
license = "MIT"
documentation = "https://docs.faust.computer"
homepage = "https://example.com"
repository = "https://github.com/faust-computer/geist_common"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geist_common = "0.1.0"  
